/*
 * This source file was generated by the Gradle 'init' task
 */
package ball;
import ball.model.Ball;
import ball.controller.BallController;

public class App {
    public static void main(String[] args) {
        Ball ball = new Ball();
        BallController controller = new BallController(ball);
    }
}
